import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Mainpage</Link>
        </li>
        <li>
          <Link to="/pluginfilecovertwo">PluginfilecoverTwo</Link>
        </li>
        <li>
          <Link to="/companents">Companents</Link>
        </li>
        <li>
          <Link to="/kinohaqidavakinokorishsaxifasi">
            Kinohaqidavakinokorishsaxifasi
          </Link>
        </li>
        <li>
          <Link to="/contact">Contact</Link>
        </li>
        <li>
          <Link to="/fullwidth">Fullwidth</Link>
        </li>
        <li>
          <Link to="/shikoyatlarcatigoriyasi">Shikoyatlarcatigoriyasi</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
